# Task Checklist
- [x] Open login page
- [x] Open login page
- [x] Click 'Criar conta'
- [x] Take screenshot of registration form
- [ ] Fill registration details
- [ ] Click 'Cadastrar e Iniciar'
- [ ] Take screenshot after registration
- [ ] Wait for login page
- [ ] Login with email 'ok@teste.com'
- [ ] Take screenshot of dashboard showing 'Teste Final Ok'
